#!/usr/bin/env node
// Reads each agent's SKILL file from ../skills/{agent}/... in the parent
// repo and writes them as a single JS module that the CLI imports at
// runtime. Run automatically before `npm publish` via prepublishOnly,
// or manually via `npm run build`.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(here, '..', '..');
const skillsDir = path.join(repoRoot, 'skills');

// Each agent has its target install path (where the file should land in the
// user's project) and its source file in the repo's skills/ tree.
const agents = [
  {
    id: 'claude',
    label: 'Claude Code',
    detect: '.claude',
    target: '.claude/skills/artofinfra/SKILL.md',
    source: 'claude/SKILL.md',
  },
  {
    id: 'cursor',
    label: 'Cursor',
    detect: '.cursor',
    target: '.cursor/rules/artofinfra.mdc',
    source: 'cursor/artofinfra.mdc',
  },
  {
    id: 'codex',
    label: 'Codex',
    detect: '.codex',
    target: '.codex/skills/artofinfra/SKILL.md',
    source: 'codex/SKILL.md',
  },
  {
    id: 'opencode',
    label: 'OpenCode',
    detect: '.opencode',
    target: '.opencode/skills/artofinfra/SKILL.md',
    source: 'opencode/SKILL.md',
  },
  {
    id: 'amp',
    label: 'Amp',
    detect: '.amp',
    target: '.amp/skills/artofinfra/SKILL.md',
    source: 'amp/SKILL.md',
  },
];

const bundled = agents.map((a) => {
  const sourcePath = path.join(skillsDir, a.source);
  const content = fs.readFileSync(sourcePath, 'utf8');
  return {
    id: a.id,
    label: a.label,
    detect: a.detect,
    target: a.target,
    content,
  };
});

const outPath = path.join(here, '..', 'lib', 'skills.js');
const out = `// Auto-generated by scripts/build-skills.js. Do not edit by hand.
// Bundles each agent's SKILL file content at npm-publish time so the
// installed CLI works offline. Regenerate via \`npm run build\`.

export const agents = ${JSON.stringify(bundled, null, 2)};
`;

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, out);

console.log(
  `Built ${outPath} with ${bundled.length} agents: ${bundled.map((a) => a.id).join(', ')}.`,
);
